### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by 7starsone** [extractr-io/puphpeteer#1]
Hello,
please, can you better explain with other examples?

Eg. after $page->goto($url);

does it mean that $page contains the page content or how to get the entire page content inside a variable?

That is, I need to surf a page as if I were in front of the screen and then extract all the hrefs of this page searching in the page content

thanks

**Comment by nesk** [comment]
PuPHPeteer is only a PHP bridge for Puppeteer, therefore [the API is the same](https://github.com/GoogleChrome/puppeteer/blob/v1.1.1/docs/api.md), only the syntax differs.

If you check [the documentation for the `goto` method](https://github.com/GoogleChrome/puppeteer/blob/v1.1.1/docs/api.md#pagegotourl-options) on the original repository, you can see it returns `Response` or `null`, it's the same for PuPHPeteer. 😉 

```php
$response = $page->goto('https://example.com');

// Prints the headers of the response
var_dump($response->headers());

// Prints the full HTML contents of the page
var_dump($page->content());
```

**Comment by 7starsone** [comment]
Hello, I did the installation as described but on error log:

Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "'node' '/home/user/public_html/tmp/pjs/vendor/extractr-io/rialto/src/node-process/serve.js' '/home/user/public_html/tmp/pjs/vendor/extractr-io/puphpeteer/src/PuppeteerConnectionDelegate.js' '{"idle_timeout":60}'" failed.

Exit Code: 1(General error)

Working directory: /home/user/public_html/tmp/pjs

Output:
================


Error Output:
================
/home/user/public_html/tmp/pjs/vendor/extractr-io/puphpeteer/src/PuppeteerConnectionDelegate.js:25
    async handleInstruction(instruction, responseHandler, errorHandler) {
          ^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:49 in /home/user/public_html/tmp/pjs/vendor/extractr-io/rialto/src/Process.php on line 232

please, what's the issue here?
thanks

**Comment by nesk** [comment]
You need Node 8 or greater.

**Comment by 7starsone** [comment]
I think you should create/update, if possible, a guide to properly run it on CentOS (at least 7) because it's a mess
https://github.com/GoogleChrome/puppeteer/issues/391#issuecomment-356822760

**Comment by nesk** [comment]
Actually, this is an issue due to Puppeteer, my bridge is not related to this. Please, see [Puppeteer's  troubleshooting guide](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) for your issues with CentOS.

Based on the guide, disabling the sandbox might help you:

```php
$puppeteer = new Puppeteer;

$browser = $puppeteer->launch([
    'args' => ['--no-sandbox', '--disable-setuid-sandbox'],
]);
```

**Comment by 7starsone** [comment]
installed dependencies, used your no sandbox...
but for `var_dump($page->content());` I always get **NULL**

**Comment by nesk** [comment]
Please, give me a fully reproducible example. This code works for me:

```php
$puppeteer = new ExtractrIo\Puphpeteer\Puppeteer;
$browser = $puppeteer->launch(['headless' => false]);
$page = $browser->newPage();
$page->goto('https://example.com');

var_dump($page->content());
```

Check also if the issue doesn't come directly from Puppeteer by using the original API in Node.js.

**Comment by 7starsone** [comment]
I have
`nodejs-9.7.1-1nodesource.x86_64`

this was installed after your installation commands, because by mistake I skipped the line where written that Node 8+ is required and on CentOS by default node 6 in installed...

anyway, may it be related?
Do I need to run that npm command again or ?

**Comment by 7starsone** [comment]
I get errors if I don't use --no sandbox only

so, 

```
require 'vendor/autoload.php';
use ExtractrIo\Puphpeteer\Puppeteer; 

$puppeteer = new Puppeteer;
$browser = $puppeteer->launch([
    'args' => ['--no-sandbox', '--disable-setuid-sandbox'],
]);
$page = $browser->newPage();
$response = $page->goto('https://example.com/');
var_dump($page->content());
$browser->close();
```
with example.com I get the result, BUT with other sites
eg. icecat.de
I get **NULL**

**Comment by nesk** [comment]
Ooooh, seems like _there is_ an issue with my code! I got the same result!

Could you create a new issue describing this? I will fix this later today or tomorrow.

**Comment by dev-ys** [comment]
This is not working for me.

```Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "'node' '.../vendor/nesk/rialto/src/node-process/serve.js' '.../vendor/nesk/puphpeteer/src/PuppeteerConnectionDelegate.js' '{"idle_timeout":60,"log_node_console":false,"log_browser_console":false}'" failed. Exit Code: 127(Command not found) Working directory: ...Output: ================ Error Output: ================ sh: line 0: exec: node: not found in .../vendor/nesk/rialto/src/ProcessSupervisor.php:309 Stack trace: #0 .../vendor/nesk/rialto/src/ProcessSupervisor.php(344): Nesk\Rialto\ProcessSupervisor->checkProcessStatus() #1 .../vendor/nesk/rialto/src/ProcessSupervisor.php(149): Nesk\Rialto\ProcessSupervisor->serverPort() #2 .../vendor/nesk/rialto/src/Abstra in .../vendor/nesk/rialto/src/ProcessSupervisor.php on line 309```

I found other library
https://github.com/its404/php-puppeteer
This is working well.

**Comment by nesk** [comment]
It seems like the `node` command is not found on your system. Until I fix this, you can use [the `executable_path` option](https://github.com/nesk/rialto/blob/master/docs/api.md#options) to provide the path to node:

```php
$puppeteer = new Puppeteer([
    'executable_path' => '/path/to/node',
]);
```
